#!/usr/bin/env bash

checkout_dir="$1"
project="$2"
update="$3"
selfdir="$PWD/$(dirname $0)"

if ! test "x$update" = "xno"; then
	update=yes
fi

set -e

if ! test "$#" -ge 2; then
	echo "Usage: $0 <checkout-root-dir> <obs-project> [<update>=yes|no]"
	exit 1
fi

if test "x$update" = "xno"; then
	echo "Skipping update of checkout of $project..."
else
	echo "Updating checkout of $project..."
	(
		mkdir -p "$checkout_dir"
		cd "$checkout_dir"
		"$selfdir/osc-checkout-project" "$project"
	)
fi

if ! test -d "$checkout_dir/$project" || \
	! test -d "$checkout_dir/$project/.osc"; then
	echo "$project is not a valid OBS checkout"
	exit 1
fi

echo "Analyzing OBS tree..."
report_path="$checkout_dir/${project##*/}-report.html"
report_path="$(echo "$report_path" | \
	tr '[:upper:]' '[:lower:]' | \
	tr ':' '-')"

mono --debug "$selfdir/text-transform.exe" \
	-P="$selfdir" \
	-I="$selfdir/Reporting" \
	-a="obs-project-path:$checkout_dir/$project" \
	-a="source-link-path:." \
	-o="$report_path" \
	"$selfdir/Reporting/report.tt"

echo "Done."
