#!/usr/bin/env bash

project="$1"
selfdir="$(dirname $0)"

set -e

if ! test "$#" -eq 1; then
	echo "Usage: $0 <obs-project>"
	exit 1
fi

echo "Updating checkout of $project..."
#"$selfdir/osc-checkout-project" "$project"

if ! test -d "$project" || ! test -d "$project/.osc"; then
	echo "$project is not a valid OBS checkout"
	exit 1
fi

echo "Analyzing OBS tree..."
report_path="${project##*/}-report.html"
report_path="$(echo "$report_path" | \
	tr '[:upper:]' '[:lower:]' | \
	tr ':' '-')"

mono --debug "$selfdir/text-transform.exe" \
	-P="$selfdir" \
	-I="$selfdir/Reporting" \
	-a="obs-project-path:$project" \
	-o="$report_path" \
	Reporting/report.tt

echo "Done."
