#!/usr/bin/env bash

DEST="moblin@moblin-build.suse.com:public_html/obs-status"
UPDATE="$1"

cd "$(dirname "$0")"

for project in Moblin:Base Moblin:UI Moblin:Factory; do
	mkdir -p "trees/$project"
	(
		flock -x 200
		./analyze trees "$project" "$UPDATE"
	) 200>"trees/$project/sync-lock"
	rm -f "trees/$project/sync-lock"
done

echo "Rsyncing to $DEST..."
rsync -avz --progress -e ssh --delete --delete-after \
		--exclude=.osc/ \
		trees/ \
		"$DEST"
